In [2]:
import sys
sys.path.append("../")
from lib.dashboard import *
from lib.graph import *
from lib.models import *
from lib.preprocess import *

ModuleNotFoundError: No module named 'xgboost'

In [4]:
file_address= '../projects/data/train.csv'
y_variable= 'Sales'
p=preprocess()
p.set_parameter('address', file_address)
p.set_parameter('y_variable', y_variable)
p.read_file()
p.filterin('Store',1)


data only contain rows with: Store == 1


/Users/labbrand/Desktop/API/env/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3183: DtypeWarning:

Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.



'data only contain rows with: Store == 1'

In [6]:
p.data.to_csv('train.csv')

In [8]:
file_address= '../projects/data/garan.csv'
y_variable= 'Actual Unit'
p1=preprocess()
p1.set_parameter('address', file_address)
p1.set_parameter('y_variable', y_variable)
p1.read_file()
p1.replace_nan(0)
p1.variables()
p1.split_time()
p1.choose_y()
p1.category_to_nominal()
p1.calculate_dim()

Nan replaced with 0. Can pass something other than 0
Variables successfully selected
File does not need time splitting
Actual Unit as y variable successfully chosen
Categoricol to nominal done!
Dim calculated


'dimensions calculated'

In [9]:
m=NN_with_EE()
project_name= 'garam'
m.build_model(project_name, p1.p['io_dim'])

../lib/models.py:108: UserWarning:

The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.

../lib/models.py:112: UserWarning:

Update your `Dense` call to the Keras 2 API: `Dense(1000, kernel_initializer="uniform")`

../lib/models.py:115: UserWarning:

Update your `Dense` call to the Keras 2 API: `Dense(200, kernel_initializer="uniform")`



In [10]:
m.fit(np.array(p1.data[:-900]),np.array(p1.data_y[:-900]),np.array(p1.data[-900:]), np.array(p1.data_y[-900:]))

Model is training
Train on 30025 samples, validate on 900 samples
Epoch 1/10
19820/30025 [==================>...........] - ETA: 8s - loss: nan

KeyboardInterrupt: 

In [3]:
project_name= 'Garan'
project_type= 'p'
file_address= '../projects/data/garan.csv'
y_variable= 'Actual Unit'
d=Dashboard(project_name, project_type)
d.set_parameter('file_address', file_address)
d.set_parameter('y_variable', y_variable)
d.transform_data(filter_in=['Member Description', ])
d.find_best_model()

reading file
Nan replaced with 0. Can pass something other than 0
Variables successfully selected
File does not need time splitting
Actual Unit as y variable successfully chosen
Categoricol to nominal done!
Dim calculated


../lib/models.py:108: UserWarning:

The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.

../lib/models.py:112: UserWarning:

Update your `Dense` call to the Keras 2 API: `Dense(1000, kernel_initializer="uniform")`

../lib/models.py:115: UserWarning:

Update your `Dense` call to the Keras 2 API: `Dense(200, kernel_initializer="uniform")`



Instructions for updating:
keep_dims is deprecated, use keepdims instead
Model is training
Train on 27832 samples, validate on 3093 samples
Epoch 1/10
27832/27832 [==============================] - 21s 769us/step - loss: nan - val_loss: nan
Epoch 2/10
27832/27832 [==============================] - 21s 743us/step - loss: nan - val_loss: nan
Epoch 3/10
15160/27832 [===============>..............] - ETA: 9s - loss: nan

KeyboardInterrupt: 

In [2]:
project_name= 'fairyMo'
project_type= 'f'
file_address= '../projects/data/train.csv'
y_variable= 'Sales'
d1= Dashboard(project_name, project_type)
d1.set_parameter('file_address', file_address)
d1.set_parameter('y_variable', y_variable)
d1.transform_data(filter_in=['Store',1])
d1.find_best_model(.9,10)

reading file


/Users/labbrand/Desktop/API/env/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3265: DtypeWarning:

Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.



data only contain rows with: Store == 1
Nan replaced with 0. Can pass something other than 0
Variables successfully selected
Removed and splitted Date!
Sales as y variable successfully chosen
Categoricol to nominal done!
Dim calculated
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Model is training
Train on 826 samples, validate on 74 samples
Epoch 1/10
Epoch 00001: val_loss improved from inf to 0.05708, saving model to ../projects/fairyMo/models/LSTM_weights.h5
 - 4s - loss: 0.1628 - val_loss: 0.0571
Epoch 2/10
Epoch 00002: val_loss improved from 0.05708 to 0.03474, saving model to ../projects/fairyMo/models/LSTM_weights.h5
 - 3s - loss: 0.0426 - val_loss: 0.0347
Epoch 3/10
Epoch 00003: val_loss improved from 0.03474 to 0.03242, saving model to ../projects/fairyMo/models/LSTM_weights.h5
 - 3s - loss: 0.0332 - val_loss: 0.0324
Epoch 4/10
Epoch 00004: val_loss improved from 0.03242 to 0.0

In [3]:
d1.forecast()

array([2.39598138e+03, 2.56207610e+03, 1.81940324e+03, 1.78172000e+03,
       2.12917437e+03, 2.80872433e+03, 5.59748268e-01, 2.11686450e+03,
       2.32536322e+03, 1.69115091e+03, 1.45591278e+03, 1.94722876e+03,
       2.76073584e+03, 1.08406912e+00, 2.12178828e+03, 2.32275552e+03,
       1.53007297e+03, 1.41755264e+03, 1.88002579e+03, 2.75098464e+03,
       2.80668635e+00, 2.12516003e+03, 2.37042838e+03, 1.53645322e+03,
       1.34588167e+03, 1.93902349e+03, 2.69653651e+03, 5.01518946e+00,
       2.15250132e+03, 2.32377119e+03])

In [3]:
project_name= 'rossman2'
m= XGBoost()
m.build_model(project_name)

In [4]:
m.fit(np.array(p.data[:900]),np.array(p.data_y[:900]),np.array(p.data[900:]),np.array(p.data_y[900:]))

[0]	train-rmse:7.09212
[1]	train-rmse:6.95055
[2]	train-rmse:6.81198
[3]	train-rmse:6.67613
[4]	train-rmse:6.54289
[5]	train-rmse:6.4125
[6]	train-rmse:6.28467
[7]	train-rmse:6.15935
[8]	train-rmse:6.0366
[9]	train-rmse:5.91611
[10]	train-rmse:5.79805
[11]	train-rmse:5.68236
[12]	train-rmse:5.56904
[13]	train-rmse:5.4582
[14]	train-rmse:5.34953
[15]	train-rmse:5.2429
[16]	train-rmse:5.13839
[17]	train-rmse:5.03606
[18]	train-rmse:4.93573
[19]	train-rmse:4.83733
[20]	train-rmse:4.74094
[21]	train-rmse:4.64632
[22]	train-rmse:4.55367
[23]	train-rmse:4.463
[24]	train-rmse:4.37416
[25]	train-rmse:4.28712
[26]	train-rmse:4.20169
[27]	train-rmse:4.11796
[28]	train-rmse:4.03603
[29]	train-rmse:3.95558
[30]	train-rmse:3.87679
[31]	train-rmse:3.79959
[32]	train-rmse:3.72393
[33]	train-rmse:3.64977
[34]	train-rmse:3.57723
[35]	train-rmse:3.50605
[36]	train-rmse:3.43627
[37]	train-rmse:3.36794
[38]	train-rmse:3.301
[39]	train-rmse:3.23537
[40]	train-rmse:3.17104
[41]	train-rmse:3.10791
[42]	train

[325]	train-rmse:0.036715
[326]	train-rmse:0.036552
[327]	train-rmse:0.036394
[328]	train-rmse:0.036221
[329]	train-rmse:0.03607
[330]	train-rmse:0.0359
[331]	train-rmse:0.035759
[332]	train-rmse:0.035602
[333]	train-rmse:0.035458
[334]	train-rmse:0.035339
[335]	train-rmse:0.035181
[336]	train-rmse:0.035088
[337]	train-rmse:0.034947
[338]	train-rmse:0.03482
[339]	train-rmse:0.03469
[340]	train-rmse:0.034576
[341]	train-rmse:0.034467
[342]	train-rmse:0.034341
[343]	train-rmse:0.03419
[344]	train-rmse:0.034088
[345]	train-rmse:0.033984
[346]	train-rmse:0.03387
[347]	train-rmse:0.03377
[348]	train-rmse:0.033681
[349]	train-rmse:0.033582
[350]	train-rmse:0.03344
[351]	train-rmse:0.033338
[352]	train-rmse:0.033254
[353]	train-rmse:0.033163
[354]	train-rmse:0.033055
[355]	train-rmse:0.032965
[356]	train-rmse:0.032877
[357]	train-rmse:0.032782
[358]	train-rmse:0.032685
[359]	train-rmse:0.032582
[360]	train-rmse:0.032481
[361]	train-rmse:0.032354
[362]	train-rmse:0.03225
[363]	train-rmse:0.032

[642]	train-rmse:0.016963
[643]	train-rmse:0.016921
[644]	train-rmse:0.016862
[645]	train-rmse:0.016834
[646]	train-rmse:0.016794
[647]	train-rmse:0.016766
[648]	train-rmse:0.016752
[649]	train-rmse:0.016722
[650]	train-rmse:0.016681
[651]	train-rmse:0.016633
[652]	train-rmse:0.01658
[653]	train-rmse:0.016531
[654]	train-rmse:0.016514
[655]	train-rmse:0.01648
[656]	train-rmse:0.016452
[657]	train-rmse:0.0164
[658]	train-rmse:0.016355
[659]	train-rmse:0.016333
[660]	train-rmse:0.016304
[661]	train-rmse:0.016276
[662]	train-rmse:0.016226
[663]	train-rmse:0.016191
[664]	train-rmse:0.016151
[665]	train-rmse:0.016123
[666]	train-rmse:0.016087
[667]	train-rmse:0.016068
[668]	train-rmse:0.016038
[669]	train-rmse:0.016002
[670]	train-rmse:0.01597
[671]	train-rmse:0.015945
[672]	train-rmse:0.0159
[673]	train-rmse:0.015867
[674]	train-rmse:0.015842
[675]	train-rmse:0.01579
[676]	train-rmse:0.015744
[677]	train-rmse:0.015689
[678]	train-rmse:0.015662
[679]	train-rmse:0.015643
[680]	train-rmse:0.0

[959]	train-rmse:0.008944
[960]	train-rmse:0.008928
[961]	train-rmse:0.008912
[962]	train-rmse:0.008895
[963]	train-rmse:0.008871
[964]	train-rmse:0.008859
[965]	train-rmse:0.008846
[966]	train-rmse:0.008828
[967]	train-rmse:0.008803
[968]	train-rmse:0.008788
[969]	train-rmse:0.008767
[970]	train-rmse:0.008748
[971]	train-rmse:0.00873
[972]	train-rmse:0.008723
[973]	train-rmse:0.008709
[974]	train-rmse:0.008689
[975]	train-rmse:0.008673
[976]	train-rmse:0.008654
[977]	train-rmse:0.008637
[978]	train-rmse:0.008624
[979]	train-rmse:0.008604
[980]	train-rmse:0.008579
[981]	train-rmse:0.008566
[982]	train-rmse:0.008548
[983]	train-rmse:0.008532
[984]	train-rmse:0.00853
[985]	train-rmse:0.008516
[986]	train-rmse:0.008502
[987]	train-rmse:0.008486
[988]	train-rmse:0.008466
[989]	train-rmse:0.008441
[990]	train-rmse:0.008424
[991]	train-rmse:0.008405
[992]	train-rmse:0.008394
[993]	train-rmse:0.008371
[994]	train-rmse:0.008359
[995]	train-rmse:0.008339
[996]	train-rmse:0.008329
[997]	train-rm

[1265]	train-rmse:0.005144
[1266]	train-rmse:0.005137
[1267]	train-rmse:0.005131
[1268]	train-rmse:0.005119
[1269]	train-rmse:0.005103
[1270]	train-rmse:0.0051
[1271]	train-rmse:0.005092
[1272]	train-rmse:0.005084
[1273]	train-rmse:0.005073
[1274]	train-rmse:0.005069
[1275]	train-rmse:0.005061
[1276]	train-rmse:0.005051
[1277]	train-rmse:0.005045
[1278]	train-rmse:0.005038
[1279]	train-rmse:0.005036
[1280]	train-rmse:0.00503
[1281]	train-rmse:0.005022
[1282]	train-rmse:0.005007
[1283]	train-rmse:0.004997
[1284]	train-rmse:0.004989
[1285]	train-rmse:0.004977
[1286]	train-rmse:0.00497
[1287]	train-rmse:0.004962
[1288]	train-rmse:0.004952
[1289]	train-rmse:0.004945
[1290]	train-rmse:0.00494
[1291]	train-rmse:0.004932
[1292]	train-rmse:0.004931
[1293]	train-rmse:0.004922
[1294]	train-rmse:0.004917
[1295]	train-rmse:0.004906
[1296]	train-rmse:0.004899
[1297]	train-rmse:0.004883
[1298]	train-rmse:0.00488
[1299]	train-rmse:0.00487
[1300]	train-rmse:0.004859
[1301]	train-rmse:0.004854
[1302]	t

[1571]	train-rmse:0.003056
[1572]	train-rmse:0.003052
[1573]	train-rmse:0.003047
[1574]	train-rmse:0.00304
[1575]	train-rmse:0.003037
[1576]	train-rmse:0.003033
[1577]	train-rmse:0.00303
[1578]	train-rmse:0.003025
[1579]	train-rmse:0.003019
[1580]	train-rmse:0.003016
[1581]	train-rmse:0.003012
[1582]	train-rmse:0.003009
[1583]	train-rmse:0.003005
[1584]	train-rmse:0.003
[1585]	train-rmse:0.002993
[1586]	train-rmse:0.002988
[1587]	train-rmse:0.00298
[1588]	train-rmse:0.002973
[1589]	train-rmse:0.002968
[1590]	train-rmse:0.002963
[1591]	train-rmse:0.002958
[1592]	train-rmse:0.002953
[1593]	train-rmse:0.002949
[1594]	train-rmse:0.002944
[1595]	train-rmse:0.002937
[1596]	train-rmse:0.002933
[1597]	train-rmse:0.002924
[1598]	train-rmse:0.002918
[1599]	train-rmse:0.002916
[1600]	train-rmse:0.002909
[1601]	train-rmse:0.002904
[1602]	train-rmse:0.002901
[1603]	train-rmse:0.002896
[1604]	train-rmse:0.002895
[1605]	train-rmse:0.002893
[1606]	train-rmse:0.002888
[1607]	train-rmse:0.002884
[1608]	

[1876]	train-rmse:0.001896
[1877]	train-rmse:0.001893
[1878]	train-rmse:0.001889
[1879]	train-rmse:0.001887
[1880]	train-rmse:0.001886
[1881]	train-rmse:0.001883
[1882]	train-rmse:0.001878
[1883]	train-rmse:0.001874
[1884]	train-rmse:0.001871
[1885]	train-rmse:0.001867
[1886]	train-rmse:0.001864
[1887]	train-rmse:0.001864
[1888]	train-rmse:0.001861
[1889]	train-rmse:0.001861
[1890]	train-rmse:0.001857
[1891]	train-rmse:0.001854
[1892]	train-rmse:0.001852
[1893]	train-rmse:0.00185
[1894]	train-rmse:0.001846
[1895]	train-rmse:0.001842
[1896]	train-rmse:0.001839
[1897]	train-rmse:0.001837
[1898]	train-rmse:0.001834
[1899]	train-rmse:0.00183
[1900]	train-rmse:0.001827
[1901]	train-rmse:0.001825
[1902]	train-rmse:0.001822
[1903]	train-rmse:0.001817
[1904]	train-rmse:0.001814
[1905]	train-rmse:0.001812
[1906]	train-rmse:0.001811
[1907]	train-rmse:0.001806
[1908]	train-rmse:0.001803
[1909]	train-rmse:0.0018
[1910]	train-rmse:0.001798
[1911]	train-rmse:0.001796
[1912]	train-rmse:0.001794
[1913

AttributeError: 'XGBoost' object has no attribute 'guess'

In [14]:
a= m.guess(np.array(p.data[900:]))

ValueError: Error when checking model : the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 8 array(s), but instead got the following list of 10 arrays: [array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       ...

In [15]:
a=[ 4.5487549e+03, -2.0449758e-03,  5.1150273e+03,  5.4124844e+03,
        5.8311650e+03,  5.9935474e+03,  6.0083091e+03,  7.0071553e+03,
        4.5572519e-03,  5.3538613e+03,  5.0845806e+03,  4.5001465e+03,
        4.3886338e+03,  3.8860903e+03,  4.0751150e+03,  1.2028217e-04,
        5.1209390e+03,  5.5874277e+03,  5.4088252e+03,  5.2909756e+03,
        5.7623330e+03,  5.5898267e+03, -1.7686486e-03,  5.6779883e+03,
        4.3004800e+03,  3.7278887e+03,  3.8269873e+03,  3.8194197e+03,
        4.8536758e+03, -3.8630962e-03,  5.0989370e+03,  4.8430942e+03,
        5.1722686e+03,  5.2438677e+03,  5.9682578e+03,  6.9498062e+03,
        7.1680546e-04,  4.8826611e+03,  4.8711289e+03,  4.4601250e+03,
        5.3373564e+03,  4.3385029e-03]

In [9]:
p.data_y[900:]

array([4409,    0, 5370, 5681, 5499, 6140, 6049, 7032,    0, 5970, 5633,
       4709, 4601, 3725, 4055,    0, 5598, 5586, 5195, 5578, 5720, 5394,
          0, 5182, 4127, 4044, 4008, 3900, 4717,    0, 4952, 4881, 4892,
       5471, 5580, 7176,    0, 4997, 4486, 4327, 5530,    0])

In [8]:
import math
500000< math.inf

True

In [23]:
def ttt(data, lag=3):
    df = pd.DataFrame(data)
    columns = [df.shift(i) for i in range(1, lag+1)]
    columns.append(df)
    df = pd.concat(columns, axis=1)
    df.fillna(0, inplace=True)
    return df

In [24]:

ttt(a)

0            0            0            0
0      0.000000     0.000000     0.000000  4548.754900
1   4548.754900     0.000000     0.000000    -0.002045
2     -0.002045  4548.754900     0.000000  5115.027300
3   5115.027300    -0.002045  4548.754900  5412.484400
4   5412.484400  5115.027300    -0.002045  5831.165000
5   5831.165000  5412.484400  5115.027300  5993.547400
6   5993.547400  5831.165000  5412.484400  6008.309100
7   6008.309100  5993.547400  5831.165000  7007.155300
8   7007.155300  6008.309100  5993.547400     0.004557
9      0.004557  7007.155300  6008.309100  5353.861300
10  5353.861300     0.004557  7007.155300  5084.580600
11  5084.580600  5353.861300     0.004557  4500.146500
12  4500.146500  5084.580600  5353.861300  4388.633800
13  4388.633800  4500.146500  5084.580600  3886.090300
14  3886.090300  4388.633800  4500.146500  4075.115000
15  4075.115000  3886.090300  4388.633800     0.000120
16     0.000120  4075.115000  3886.090300  5120.939000
17  5120.939000     0.000120  4075.115000  5587.427700
18  5587.427700  5120.939000     0.000120  5408.825200
19  5408.825200  5587.427700  5120.939000  5290.975600
20  5290.975600  5408.825200  5587.427700  5762.333000
21  5762.333000  5290.975600  5408.825200  5589.826700
22  5589.826700  5762.333000  5290.975600    -0.001769
23    -0.001769  5589.826700  5762.333000  5677.988300
24  5677.988300    -0.001769  5589.826700  4300.480000
25  4300.480000  5677.988300    -0.001769  3727.888700
26  3727.888700  4300.480000  5677.988300  3826.987300
27  3826.987300  3727.888700  4300.480000  3819.419700
28  3819.419700  3826.987300  3727.888700  4853.675800
29  4853.675800  3819.419700  3826.987300    -0.003863
30    -0.003863  4853.675800  3819.419700  5098.937000
31  5098.937000    -0.003863  4853.675800  4843.094200
32  4843.094200  5098.937000    -0.003863  5172.268600
33  5172.268600  4843.094200  5098.937000  5243.867700
34  5243.867700  5172.268600  4843.094200  5968.257800
35  5968.257800  5243.867700  5172.268600  6949.806200
36  6949.806200  5968.257800  5243.867700     0.000717
37     0.000717  6949.806200  5968.257800  4882.661100
38  4882.661100     0.000717  6949.806200  4871.128900
39  4871.128900  4882.661100     0.000717  4460.125000
40  4460.125000  4871.128900  4882.661100  5337.356400
41  5337.356400  4460.125000  4871.128900     0.004339

In [122]:
def create_dataset(dataset, look_back=1):
    dataX, dataY = [], []
    for i in range(len(dataset)-look_back):
        b = dataset[i:(i+look_back)]
        dataX.append(b)
        dataY.append(dataset[i + look_back])
    return numpy.array(dataX), numpy.array(dataY)

In [123]:
create_dataset([1,2,3,4],2)

(array([[1, 2],
        [2, 3]]), array([3, 4]))

In [111]:
def create_dataset_per(d, lockback=4):
    return numpy.array([d])

In [125]:
x[-3:]

array([[1, 2, 3]])

In [114]:
X = numpy.reshape(x, (x.shape[0], 1, x.shape[1]))

In [77]:
y= numpy.reshape(x[0],(-1, 4))

In [119]:
X.append()

array([[[2, 4, 6]]])

In [117]:
# create and fit the LSTM network
look_back=3
model = Sequential()
model.add(LSTM(4, input_shape=(1, look_back)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(X, y, epochs=100, batch_size=1, verbose=2)

Epoch 1/100
 - 1s - loss: 17.6907
Epoch 2/100
 - 0s - loss: 17.6476
Epoch 3/100
 - 0s - loss: 17.6048
Epoch 4/100
 - 0s - loss: 17.5624
Epoch 5/100
 - 0s - loss: 17.5203
Epoch 6/100
 - 0s - loss: 17.4802
Epoch 7/100
 - 0s - loss: 17.4387
Epoch 8/100
 - 0s - loss: 17.3976
Epoch 9/100
 - 0s - loss: 17.3573
Epoch 10/100
 - 0s - loss: 17.3168
Epoch 11/100
 - 0s - loss: 17.2766
Epoch 12/100
 - 0s - loss: 17.2368
Epoch 13/100
 - 0s - loss: 17.1973
Epoch 14/100
 - 0s - loss: 17.1581
Epoch 15/100
 - 0s - loss: 17.1192
Epoch 16/100
 - 0s - loss: 17.0806
Epoch 17/100
 - 0s - loss: 17.0424
Epoch 18/100
 - 0s - loss: 17.0044
Epoch 19/100
 - 0s - loss: 16.9667
Epoch 20/100
 - 0s - loss: 16.9290
Epoch 21/100
 - 0s - loss: 16.8919
Epoch 22/100
 - 0s - loss: 16.8551
Epoch 23/100
 - 0s - loss: 16.8186
Epoch 24/100
 - 0s - loss: 16.7823
Epoch 25/100
 - 0s - loss: 16.7464
Epoch 26/100
 - 0s - loss: 16.7106
Epoch 27/100
 - 0s - loss: 16.6747
Epoch 28/100
 - 0s - loss: 16.6391
Epoch 29/100
 - 0s - loss: 16

In [8]:
np.concatenate(np.array([1,2,3]),np.array([1,2,3]))

TypeError: only integer scalar arrays can be converted to a scalar index

In [9]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [128]:
p1.data_y

array([312., 528., 708., ...,  nan,  nan,  nan])

In [3]:
m=time_series()
project_name= 'forecast'
m.build_model(project_name)

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [4]:
y= p.data_y[::-1]
m.fit(y[:900],y[900:])

Model is training
Train on 879 samples, validate on 21 samples
Epoch 1/100
Epoch 00001: val_loss improved from inf to 0.02869, saving model to ../projects/forecast/models/LSTM_weights.h5
 - 3s - loss: 0.1624 - val_loss: 0.0287
Epoch 2/100
Epoch 00002: val_loss improved from 0.02869 to 0.00291, saving model to ../projects/forecast/models/LSTM_weights.h5
 - 2s - loss: 0.0436 - val_loss: 0.0029
Epoch 3/100
Epoch 00003: val_loss improved from 0.00291 to 0.00189, saving model to ../projects/forecast/models/LSTM_weights.h5
 - 2s - loss: 0.0359 - val_loss: 0.0019
Epoch 4/100
Epoch 00004: val_loss improved from 0.00189 to 0.00143, saving model to ../projects/forecast/models/LSTM_weights.h5
 - 2s - loss: 0.0335 - val_loss: 0.0014
Epoch 5/100
Epoch 00005: val_loss improved from 0.00143 to 0.00112, saving model to ../projects/forecast/models/LSTM_weights.h5
 - 2s - loss: 0.0319 - val_loss: 0.0011
Epoch 6/100
Epoch 00006: val_loss improved from 0.00112 to 0.00059, saving model to ../projects/forec

Epoch 83/100
Epoch 00083: val_loss did not improve
 - 2s - loss: 0.0192 - val_loss: 0.0020
Epoch 84/100
Epoch 00084: val_loss did not improve
 - 2s - loss: 0.0194 - val_loss: 9.4949e-04
Epoch 85/100
Epoch 00085: val_loss did not improve
 - 2s - loss: 0.0190 - val_loss: 0.0017
Epoch 86/100
Epoch 00086: val_loss did not improve
 - 2s - loss: 0.0188 - val_loss: 0.0028
Epoch 87/100
Epoch 00087: val_loss did not improve
 - 2s - loss: 0.0193 - val_loss: 9.3599e-04
Epoch 88/100
Epoch 00088: val_loss did not improve
 - 2s - loss: 0.0189 - val_loss: 8.2425e-04
Epoch 89/100
Epoch 00089: val_loss did not improve
 - 2s - loss: 0.0191 - val_loss: 0.0045
Epoch 90/100
Epoch 00090: val_loss did not improve
 - 2s - loss: 0.0188 - val_loss: 0.0011
Epoch 91/100
Epoch 00091: val_loss did not improve
 - 2s - loss: 0.0187 - val_loss: 8.6387e-04
Epoch 92/100
Epoch 00092: val_loss did not improve
 - 2s - loss: 0.0187 - val_loss: 5.9104e-04
Epoch 93/100
Epoch 00093: val_loss did not improve
 - 2s - loss: 0.018

In [3]:
m.forecast(30)

NameError: name 'm' is not defined

In [10]:
x= m.param['memory']

In [6]:
y[900:]

array([4097,    0, 3846, 3762, 3346, 3533, 3317, 4019,    0, 5197, 5735,
       5223, 5558, 4665, 4797,    0, 4359, 3650, 3797, 3897, 3808, 3530,
          0, 5054, 5042, 4767, 4427, 4852, 4406,    0, 4395, 3558, 3464,
       3769, 3706, 4364,    0, 6102, 5011, 4782, 5020, 5263])

In [8]:
y[900:]

array([4097,    0, 3846, 3762, 3346, 3533, 3317, 4019,    0, 5197, 5735,
       5223, 5558, 4665, 4797,    0, 4359, 3650, 3797, 3897, 3808, 3530,
          0, 5054, 5042, 4767, 4427, 4852, 4406,    0, 4395, 3558, 3464,
       3769, 3706, 4364,    0, 6102, 5011, 4782, 5020, 5263])

In [8]:
p.data_y[0:5]

array([5263, 5020, 4782, 5011, 6102])